development:
  adapter: mysql
  database: learnstat_development
  user: root
  <% if `hostname` =~ /^phoenix/ %>
  host: chimera
  password: j4s0nd80
  <% else %>
  password: doc1291
  socket: /tmp/mysql.sock
  <% end %>
