# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "announcements", :force => true do |t|
    t.integer  "course_id"
    t.integer  "user_id"
    t.string   "title"
    t.text     "body"
    t.datetime "created_at"
  end

  create_table "audits", :force => true do |t|
    t.integer  "user_id"
    t.text     "params"
    t.string   "url"
    t.string   "ip"
    t.datetime "created_at"
  end

  create_table "courses", :force => true do |t|
    t.string   "title"
    t.string   "department"
    t.string   "number"
    t.integer  "semester"
    t.integer  "year"
    t.integer  "section"
    t.string   "registration_code"
    t.datetime "registration_closed_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "documents", :force => true do |t|
    t.integer  "course_id"
    t.integer  "user_id"
    t.string   "label"
    t.datetime "viewable_at"
    t.string   "content_type"
    t.string   "filename"
    t.integer  "size"
    t.datetime "created_at"
  end

  create_table "grades", :force => true do |t|
    t.integer "user_id"
    t.integer "quiz_id"
    t.float   "value"
  end

  create_table "question_choices", :force => true do |t|
    t.integer "question_id"
    t.text    "content"
  end

  add_index "question_choices", ["question_id"], :name => "index_question_choices_on_question_id"

  create_table "question_responses", :force => true do |t|
    t.integer "user_id"
    t.integer "course_id"
    t.integer "quiz_id"
    t.integer "quiz_question_id"
    t.integer "question_choice_id"
    t.boolean "correct"
  end

  create_table "questions", :force => true do |t|
    t.text    "content"
    t.integer "answer"
    t.integer "chapter"
  end

  create_table "quiz_questions", :force => true do |t|
    t.integer "quiz_id"
    t.integer "question_id"
    t.boolean "forgiven",    :default => false
  end

  create_table "quizzes", :force => true do |t|
    t.integer  "course_id"
    t.string   "name"
    t.datetime "due_at"
    t.datetime "viewable_at"
    t.datetime "created_at"
  end

  create_table "users", :force => true do |t|
    t.integer  "course_id"
    t.string   "login"
    t.string   "email"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "blackboard_username"
    t.string   "registration_code"
    t.boolean  "instructor",                              :default => false
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
    t.string   "activation_code",           :limit => 40
    t.datetime "activated_at"
  end

end
